package com.ScienceStation.app.model.enumeration;

public enum NotificationType {
    CREATED_JOURNAL,JOURNAL_RETURNED_WITH_NO_REVIEW,PICK_REVIEWERS,REVIEW_JOURNAL,REVIEW_DONE,REPICK_REVIEWER,
    JOURNAL_RETURNED__WITH_REVIEW_SMALL,JOURNAL_RETURNED_WITH_REVIEW_BIG,AUTHOR_CHANGES
}
